---
title: "ManuscriptMetaPlotFigures"
author: "JA Myers"
date: "07/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

make sandi meta plot figures in R that are 
svg format, have dashed lines, and the theme_classic background

```{r}
format <- function(obj) {
  data <- obj[2:5,2:length(obj[2,])]
  return(t(data))
}
library(smoother)
```

```{r}
data <- read.delim(file="../arid1a.meta.SB1K27ac.data.txt", sep="\t", row.names = 1, stringsAsFactors = FALSE)
rownames(data)
dcaf5_H3K27ac_SB1 <- as.data.frame(format(data))
head(dcaf5_H3K27ac_SB1)
class(dcaf5_H3K27ac_SB1)
length(dcaf5_H3K27ac_SB1$`SMARCB1-H3K27ac`)
bins <- seq(-2000,2000, by= 10)
bins2 <- seq(-2000,2000, by= 20)
final_bins <- c(bins[1:200], bins[201:399], 1990)
final_bins 
length(final_bins)
df <- data.frame(final_bins,dcaf5_H3K27ac_SB1$`SMARCB1-H3K27ac`,dcaf5_H3K27ac_SB1$`SMARCB1+H3K27ac` )
tail(df)
```

define max for mark 

```{r}
max <- max(dcaf5_H3K27ac_SB1$`SMARCB1+H3K27ac`)
df$dcaf5_H3K27ac_SB1..SMARCB1.H3K27ac._div <- df$dcaf5_H3K27ac_SB1..SMARCB1.H3K27ac./max
df$dcaf5_H3K27ac_SB1..SMARCB1.H3K27ac..1 <- df$dcaf5_H3K27ac_SB1..SMARCB1.H3K27ac..1/max
```

```{r}
library(ggplot2)

axis <- c("-2kb", rep("",98), "peak center",rep("",99), "+2kb")

g <- ggplot(df, aes(x=final_bins))
g <- g +
  geom_line(aes(y=smth(df$dcaf5_H3K27ac_SB1..SMARCB1.H3K27ac._div,window = 0.1,method = "gaussian")), colour="#6C4500", size=1.2, linetype="dashed")+
  geom_line(aes(y=smth(df$dcaf5_H3K27ac_SB1..SMARCB1.H3K27ac..1,window = 0.1,method = "gaussian")), colour="#6C4500", size=1.2)+ylab(label = "dcaf5_H3K27ac_SB1 Normalized Coverage")+xlab(label = "Distance (bp)")
g + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))+ylim(0,1)


g <- ggplot(df, aes(x=final_bins))
g <- g +
  geom_line(aes(y=smth(df$dcaf5_H3K27ac_SB1..SMARCB1.H3K27ac._div,window = 0.1,method = "gaussian")), colour="#6C4500", size=1.2, linetype="dashed")+
  geom_line(aes(y=smth(df$dcaf5_H3K27ac_SB1..SMARCB1.H3K27ac..1,window = 0.1,method = "gaussian")), colour="#6C4500", size=1.2)+ylab(label = "dcaf5_H3K27ac_SB1 Normalized Coverage")+xlab(label = "Distance (bp)")
final <- g + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))+ylim(0,1)
ggsave(file="dcaf5_H3K27ac_SB1_metaplot.svg", plot=final, width = 5, height = 5)
```

```{r}
sessionInfo()
```